# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podget < Formula
  desc "Podcast downloader CLI — download episodes from RSS feeds with parallel workers, ID3 tagging, and M3U playlists"
  homepage "https://github.com/ohmylock/podget"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohmylock/podget/releases/download/v0.1.0/podget_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1e961021aaec07565a91219721da9520bd8f6945a921d9bf573628bb142fdcd"

      def install
        bin.install "podget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohmylock/podget/releases/download/v0.1.0/podget_0.1.0_darwin_arm64.tar.gz"
      sha256 "d32f21875cbb5558e0e8d10924b9753bde65e1bb25b207cf76ab46fd4e1ec5e0"

      def install
        bin.install "podget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podget/releases/download/v0.1.0/podget_0.1.0_linux_amd64.tar.gz"
      sha256 "34a8f3505ac4b04cc8a421bd3905d8347f55844a8584fdc5f6652128a3177f6b"
      def install
        bin.install "podget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podget/releases/download/v0.1.0/podget_0.1.0_linux_arm64.tar.gz"
      sha256 "2c953f37025e9c70ff290c5a8fc8be9fd70444bafe79a9224a5f58aef43dad8a"
      def install
        bin.install "podget"
      end
    end
  end
end
