# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glenv < Formula
  desc "Sync .env files to GitLab CI/CD variables — bulk import, export, and manage environment variables via CLI"
  homepage "https://github.com/ohmylock/glenv"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohmylock/glenv/releases/download/v0.1.1/glenv_0.1.1_darwin_amd64.tar.gz"
      sha256 "f759cebbb700de07c4f8ba7b53728881e9bfee1140c86206073b9df7073471ce"

      def install
        bin.install "glenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohmylock/glenv/releases/download/v0.1.1/glenv_0.1.1_darwin_arm64.tar.gz"
      sha256 "80b5ee40db6d783295251fe8ebf4d07a370cffd4f468aca26f4d8f2160d6a5c1"

      def install
        bin.install "glenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/glenv/releases/download/v0.1.1/glenv_0.1.1_linux_amd64.tar.gz"
      sha256 "786db5e5d6fcf150883031ba4b6be33e123c11d552277a85bab558cc16d8b5a5"
      def install
        bin.install "glenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/glenv/releases/download/v0.1.1/glenv_0.1.1_linux_arm64.tar.gz"
      sha256 "634e500601f9ed34f3dc38b315946bc1d7ff19fab11d88d97173b7bbff3f0db9"
      def install
        bin.install "glenv"
      end
    end
  end

  test do
    system "#{bin}/glenv", "version"
  end
end
