# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podgen < Formula
  desc "Upload MP3 episodes to S3 and generate RSS feeds for podcast players"
  homepage "https://github.com/ohmylock/podgen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.0/podgen_0.1.0_darwin_amd64.tar.gz"
      sha256 "15f9bf65e4d7520b1bcb04d0258a66def5cc8d284ee6059e35495d8a2c080116"

      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.0/podgen_0.1.0_darwin_arm64.tar.gz"
      sha256 "4d382ee6e1c549e472fcb6904ece8a5db64d9e6634b1ebf91af8899817a5d9c6"

      def install
        bin.install "podgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.0/podgen_0.1.0_linux_amd64.tar.gz"
      sha256 "f5ea006115d0498aeb631312db5c214f6127d9166b0586f3f65e878f14e34093"
      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.0/podgen_0.1.0_linux_arm64.tar.gz"
      sha256 "fab9ae06510f3c7e21e094cecda87e03bb04099a11eb6bd91c8eed9b64701c82"
      def install
        bin.install "podgen"
      end
    end
  end

  test do
    system "#{bin}/podgen", "--help"
  end
end
