# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podgen < Formula
  desc "Upload MP3 episodes to S3 and generate RSS feeds for podcast players"
  homepage "https://github.com/ohmylock/podgen"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_darwin_amd64.tar.gz"
      sha256 "f509d66252911f7dffdfb50b24ace047c7731caa840106d463cea5dc8926ca27"

      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_darwin_arm64.tar.gz"
      sha256 "1bcbfc08d2d5bda0bfd166c03ccf3a5eb3d3271d873fb7c5923b7ad68000db9a"

      def install
        bin.install "podgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_linux_amd64.tar.gz"
      sha256 "3aace6c9fda9e7574a994a8f8184bdd9f4a18216c38f798919fe1ce21a1c1dd4"
      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_linux_arm64.tar.gz"
      sha256 "3b2b909656de4b28c1ab203e3fdd89087d972650b4faa95b2b49279a53a0ea5d"
      def install
        bin.install "podgen"
      end
    end
  end

  test do
    system "#{bin}/podgen", "--help"
  end
end
