# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podgen < Formula
  desc "Upload MP3 episodes to S3 and generate RSS feeds for podcast players"
  homepage "https://github.com/ohmylock/podgen"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_darwin_amd64.tar.gz"
      sha256 "6116d23a00e54177dd8a00f5a7c1311c008cca5429d2bda1bee0a1f9c08d7756"

      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_darwin_arm64.tar.gz"
      sha256 "108ca40916b7d3c247333b34aff8aa9d29c50474823d77188e6667061daa48ef"

      def install
        bin.install "podgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_linux_amd64.tar.gz"
      sha256 "1c9ac0d781aa670e3c28d2946490bc3fe4b909d6a3ec16d3793a3e9b4473262b"
      def install
        bin.install "podgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohmylock/podgen/releases/download/v0.1.1/podgen_0.1.1_linux_arm64.tar.gz"
      sha256 "953f24274d40ac91a0c1b467103ea06ceb00742ad26cb6430e75836f84cae671"
      def install
        bin.install "podgen"
      end
    end
  end

  test do
    system "#{bin}/podgen", "--help"
  end
end
